// SPDX-License-Identifier: GPL-2.0-only

package designer

import (
	"encoding/json"
	"fmt"

	"oblikovati.org/api/types"
)

// MotorSpecSet is the attribute-set name the add-in stamps on a generated Motor assembly to
// mark it (and carry its design). A document carrying this set is a motor-designer assembly,
// so the add-in can recognise an opened design and rebuild/adjust it from the stored Spec.
const MotorSpecSet = "com.oblikovati.motor-designer"

// specAttr is the attribute name under MotorSpecSet holding the JSON-serialized Spec.
const specAttr = "spec"

// saveSpec stamps the design Spec onto a document as a JSON attribute, so re-opening the
// assembly later (or another add-in session) can recover the exact inputs that built it.
// Storing the whole Spec as one JSON string keeps the attribute schema-stable as the Spec
// grows (no per-field attribute churn).
func (e *Engine) saveSpec(documentID uint64, s Spec) error {
	blob, err := json.Marshal(s)
	if err != nil {
		return fmt.Errorf("marshal spec: %w", err)
	}
	_, err = e.api.Attributes().Set(documentID, MotorSpecSet, specAttr, types.StringVariant(string(blob)))
	if err != nil {
		return fmt.Errorf("save motor spec: %w", err)
	}
	return nil
}

// LoadSpec reads the design Spec previously stamped on a document, returning ok=false when
// the document is not a motor-designer assembly (no spec attribute). This is how a follow-up
// recognises an opened motor and recovers its parameters.
func (e *Engine) LoadSpec(documentID uint64) (Spec, bool, error) {
	res, err := e.api.Attributes().Get(documentID, MotorSpecSet, specAttr)
	if err != nil {
		return Spec{}, false, fmt.Errorf("read motor spec: %w", err)
	}
	if !res.Found {
		return Spec{}, false, nil
	}
	str, ok := res.Attribute.Value.Str()
	if !ok {
		return Spec{}, false, fmt.Errorf("motor spec attribute is not a string (got %s)", res.Attribute.Value.Type())
	}
	var s Spec
	if err := json.Unmarshal([]byte(str), &s); err != nil {
		return Spec{}, false, fmt.Errorf("decode motor spec %q: %w", str, err)
	}
	return s, true, nil
}

// IsMotorAssembly reports whether a document carries the motor-designer attribute set — i.e.
// it was generated by this add-in. A follow-up uses this to decide whether to offer a
// rebuild/adjust action for the active document.
func (e *Engine) IsMotorAssembly(documentID uint64) (bool, error) {
	_, ok, err := e.LoadSpec(documentID)
	return ok, err
}
